openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rater API
paths:
  /rate:
    post:
      summary: Rate a product for a specific Brand in a given date time
      operationId: rateProduct
      requestBody:
        description: A valid brand, product and a date time
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RateRequest"
            example:
              brandId: 1
              productId: 35455
              applyDate: 2020-06-14-00.00.00
      responses:
        "200":
          description: Product was rated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RateResponse"
                example:
                  brandId: 1
                  productId: 35455
                  startDate: 2020-06-14-00.00.00
                  endDate: 2020-12-31-23.59.59
                  priceList: 1
                  finalPrice: 35.50
        "400":
          description: 400 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 1
                message: Bad request
        "404":
          description: 404 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 2
                message: Not Found
        "500":
          description: 500 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 3
                message: Some internal error
components:
  schemas:
    RateRequest:
      type: object
      required:
        - brandId
        - productId
        - applyDate
      properties:
        brandId:
          type: integer
          format: int64
          description: A valid Brand code
        productId:
          type: integer
          format: int64
          description: A valid Product code
        applyDate:
          type: string
          format: date-time
          description: A valid date time
    RateResponse:
      type: object
      required:
        - brandId
        - productId
        - startDate
        - endDate
        - priceList
        - finalPrice
      properties:
        brandId:
          type: integer
          format: int64
          description: The brand for which the product was rated
        productId:
          type: integer
          format: int64
          description: The rated product code
        startDate:
          type: string
          format: date-time
          description: Begginning date time of the applied rate
        endDate:
          type: string
          format: date-time
          description: The end date time of the applied rate
        priceList:
          type: integer
          format: int64
          description: The code of the price list applied
        finalPrice:
          type: number
          format: float
          description: The monetary value according the applied price list
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: The error code
        message:
          type: string
          description: A detail of what happened